version: "3.9"
services:
  uscan-backend:
    image: uscan:latest
    restart: always
    command: ["--rpc_urls=wss://testnet.ankr.com/ws","--db_path=/app/uscandb","--db_path=/app/uscanforkdb"]
    volumes:
      - ./data:/app/uscandb
      - ./data:/app/uscanforkdb
    ports:
      - "4322:4322"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    networks:
      - uscan-local
    stop_grace_period: 1m30s
    stop_signal: SIGINT
networks:
  uscan-local:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.113.0/24